name: checksheet
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  excel: ^4.0.6
  path_provider: ^2.1.3
  shared_preferences: ^2.2.3
  permission_handler: ^11.3.1
  path: ^1.9.0
  file_picker: ^8.1.7
  # ❗ flutter_pdfview 삭제 후 최신 pdfrx 탑재
  pdfrx: ^2.2.24

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
